y1 = zeros(1,5);
y2 = zeros(1,1112);
hAxes = axes('NextPlot','add',...          
             'DataAspectRatio',[1 1 1],...  
             'XLim',[0 25],...               
             'YLim',[0 eps],...            
             'Color','none');               
hold on
plot(cuts, y1, 'ko', 'MarkerFaceColor',[.49 1 .63])
plot(nocuts, y2, 'ko', 'MarkerFaceColor',[1 0 0])
xlabel('SAD')